// <auto-generated />
using System;
using Aurora.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuroraIcu.Api.Core.Persistence.Migrations
{
    [DbContext(typeof(AuroraDb))]
    [Migration("20260716135330_AddPatientAssignments")]
    partial class AddPatientAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurora.Core.Adt.BedRow", b =>
                {
                    b.Property<string>("BedId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("BedId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("Aurora.Core.Adt.Encounter", b =>
                {
                    b.Property<string>("EncounterId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("AdmittedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdmittedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Attending")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DischargedAt")
                        .HasColumnType("text");

                    b.Property<string>("DischargedBy")
                        .HasColumnType("text");

                    b.Property<string>("Disposition")
                        .HasColumnType("text");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<string>("MeasurementsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("EncounterId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("Aurora.Core.Adt.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("IdentityJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameFamily")
                        .HasColumnType("text");

                    b.Property<string>("NameFirst")
                        .HasColumnType("text");

                    b.Property<string>("NameFourth")
                        .HasColumnType("text");

                    b.Property<string>("NameSecond")
                        .HasColumnType("text");

                    b.Property<string>("NameThird")
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.ToTable("AdtPatients");
                });

            modelBuilder.Entity("Aurora.Core.Ai.AiRiskRow", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.ToTable("AiRisks");
                });

            modelBuilder.Entity("Aurora.Core.Assignments.PatientAssignment", b =>
                {
                    b.Property<string>("AssignmentId")
                        .HasColumnType("text");

                    b.Property<string>("AssignedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignedByRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndReason")
                        .HasColumnType("text");

                    b.Property<string>("EndedAt")
                        .HasColumnType("text");

                    b.Property<string>("EndedBy")
                        .HasColumnType("text");

                    b.Property<string>("EndedByRole")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssignmentId");

                    b.ToTable("PatientAssignments");
                });

            modelBuilder.Entity("Aurora.Core.Identity.UserRow", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aurora.Core.LabImaging.ImagingStudyRow", b =>
                {
                    b.Property<string>("StudyId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("AcknowledgedAt")
                        .HasColumnType("text");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("text");

                    b.Property<string>("AmendmentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentedAt")
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Impression")
                        .HasColumnType("text");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("OrderedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedAt")
                        .HasColumnType("text");

                    b.Property<string>("Report")
                        .HasColumnType("text");

                    b.Property<string>("ReportedAt")
                        .HasColumnType("text");

                    b.Property<string>("ReportingRadiologist")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudyId");

                    b.ToTable("ImagingStudies");
                });

            modelBuilder.Entity("Aurora.Core.LabImaging.LabDrawRow", b =>
                {
                    b.Property<string>("LabId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("AcknowledgedAt")
                        .HasColumnType("text");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("text");

                    b.Property<string>("AmendmentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollectedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Custom")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomRefRange")
                        .HasColumnType("text");

                    b.Property<string>("CustomUnit")
                        .HasColumnType("text");

                    b.Property<string>("CustomValue")
                        .HasColumnType("text");

                    b.Property<string>("DocumentedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("Panel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabId");

                    b.ToTable("LabDraws");
                });

            modelBuilder.Entity("Aurora.Core.MasterData.FormularyDrugRow", b =>
                {
                    b.Property<string>("DrugId")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AllergyBlockJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllergyWarnJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrandNamesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultDose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoseLimitsJson")
                        .HasColumnType("text");

                    b.Property<string>("DosesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrugClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrequenciesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrnCapable")
                        .HasColumnType("boolean");

                    b.Property<string>("RoutesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DrugId");

                    b.ToTable("FormularyDrugs");
                });

            modelBuilder.Entity("Aurora.Core.MasterData.InteractionRuleRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InteractionRules");
                });

            modelBuilder.Entity("Aurora.Core.MasterData.LabTestRow", b =>
                {
                    b.Property<string>("TestId")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AnalytesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Specimen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestId");

                    b.ToTable("LabTests");
                });

            modelBuilder.Entity("Aurora.Core.MasterData.NamedFrequencyRow", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("Value");

                    b.ToTable("NamedFrequencies");
                });

            modelBuilder.Entity("Aurora.Core.MasterData.OrderSetRow", b =>
                {
                    b.Property<string>("SetId")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("SetId");

                    b.ToTable("OrderSets");
                });

            modelBuilder.Entity("Aurora.Core.Observations.ObservationGroupRow", b =>
                {
                    b.Property<string>("GroupCode")
                        .HasColumnType("text");

                    b.Property<string>("ChangedAt")
                        .HasColumnType("text");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("GroupCode");

                    b.ToTable("ObservationGroups");
                });

            modelBuilder.Entity("Aurora.Core.Observations.ObservationRow", b =>
                {
                    b.Property<string>("ObservationId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("AmendmentsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClinicalTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnteredAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("text");

                    b.HasKey("ObservationId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Aurora.Core.Observations.ObservationTypeRow", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasColumnType("text");

                    b.Property<string>("AllowedValuesJson")
                        .HasColumnType("text");

                    b.Property<string>("ComponentsJson")
                        .HasColumnType("text");

                    b.Property<string>("DerivationInputsJson")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDerived")
                        .HasColumnType("boolean");

                    b.Property<double?>("Max")
                        .HasColumnType("double precision");

                    b.Property<double?>("Min")
                        .HasColumnType("double precision");

                    b.Property<bool>("Optional")
                        .HasColumnType("boolean");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TypeCode");

                    b.ToTable("ObservationTypes");
                });

            modelBuilder.Entity("Aurora.Core.Orders.OrderRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("AdministrationsJson")
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncounterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationJson")
                        .HasColumnType("text");

                    b.Property<string>("OrderedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderedTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("RequiresImplementation")
                        .HasColumnType("boolean");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestId")
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Aurora.Modules.Icu.Roster.PatientRow", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Attending")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedAlertJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedsideVitalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Isolation")
                        .HasColumnType("boolean");

                    b.Property<int>("Los")
                        .HasColumnType("integer");

                    b.Property<string>("MapTrendJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonitorVitalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgansJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rhythm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
