// <auto-generated />
using System;
using Aurora.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aurora.Core.Persistence.Migrations
{
    [DbContext(typeof(AuroraDb))]
    [Migration("20260709173030_AddAdt")]
    partial class AddAdt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurora.Core.Adt.BedRow", b =>
                {
                    b.Property<string>("BedId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.HasKey("BedId");

                    b.ToTable("Beds");
                });

            modelBuilder.Entity("Aurora.Core.Adt.Encounter", b =>
                {
                    b.Property<string>("EncounterId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("AdmittedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdmittedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Attending")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DischargedAt")
                        .HasColumnType("text");

                    b.Property<string>("DischargedBy")
                        .HasColumnType("text");

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EncounterId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("Aurora.Core.Adt.Patient", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.ToTable("AdtPatients");
                });

            modelBuilder.Entity("Aurora.Core.Ai.AiRiskRow", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.ToTable("AiRisks");
                });

            modelBuilder.Entity("Aurora.Core.Identity.UserRow", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aurora.Core.LabImaging.ImagingStudyRow", b =>
                {
                    b.Property<string>("StudyId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("AcknowledgedAt")
                        .HasColumnType("text");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Impression")
                        .HasColumnType("text");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OrderedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerformedAt")
                        .HasColumnType("text");

                    b.Property<string>("Report")
                        .HasColumnType("text");

                    b.Property<string>("ReportedAt")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudyId");

                    b.ToTable("ImagingStudies");
                });

            modelBuilder.Entity("Aurora.Core.LabImaging.LabDrawRow", b =>
                {
                    b.Property<string>("LabId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("AcknowledgedAt")
                        .HasColumnType("text");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollectedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Panel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabId");

                    b.ToTable("LabDraws");
                });

            modelBuilder.Entity("Aurora.Core.Orders.OrderRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("AdministrationsJson")
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationJson")
                        .HasColumnType("text");

                    b.Property<string>("OrderedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderedTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("RequiresImplementation")
                        .HasColumnType("boolean");

                    b.Property<int>("Seq")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Aurora.Modules.Icu.Roster.PatientRow", b =>
                {
                    b.Property<string>("PatientId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Attending")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedAlertJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BedsideVitalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ews")
                        .HasColumnType("integer");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Isolation")
                        .HasColumnType("boolean");

                    b.Property<int>("Los")
                        .HasColumnType("integer");

                    b.Property<string>("MapTrendJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonitorVitalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgansJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rhythm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sofa")
                        .HasColumnType("integer");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
